variables:
  DOCKER_USER: ci
  COMMON_VERSION: 0.6.0
  APP_ENV: Prod
  APP_NAME: trivialsec
  BUILD_ENV: production
  AWS_REGION: ap-southeast-2

before_script:
  - touch .env
  - make --version
  - aws --version
  - docker --version
  - pylint --version
  - echo semgrep $(semgrep --version)

stages:
  - tests
  - build
  - deploy

test:sast:
  tags:
    - linode
  stage: tests
  script:
    - make semgrep-sast-ci
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: sast-results
    paths:
      - semgrep-ci.json

test:xss:
  tags:
    - linode
  stage: tests
  script:
    - make semgrep-xss-ci
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: xss-results
    paths:
      - semgrep-flask-xss.json

test:lint:
  tags:
    - linode
  stage: tests
  script:
    - make pylint-ci
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: lint-results
    paths:
      - pylint.json

build:docker:
  tags:
    - linode
  stage: build
  script:
    - make docker-login
    - make build-ci
  only:
    refs:
      - merge_request
      - main

push:docker:
  tags:
    - linode
  stage: deploy
  script:
    - make docker-login
    - make push-ci
  only:
    refs:
      - main
