version: '3.9'
services:
  api:
    env_file: .env
    image: "registry.gitlab.com/trivialsec/public-api/${BUILD_ENV}:${IMAGE_TAG:-latest}"
    container_name: api
    environment:
      - APP_ENV=${APP_ENV:-Dev}
      - APP_NAME=${APP_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - AWS_ACCESS_KEY_ID=${TF_VAR_aws_access_key_id}
      - AWS_SECRET_ACCESS_KEY=${TF_VAR_aws_secret_access_key}
      - AWS_REGION=${AWS_REGION}
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5081
    ports:
      - 5081:5081
    volumes:
      - ./src/app:/srv/app/app
      - ./src/routes:/srv/app/routes
      - ./src/services:/srv/app/services
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    healthcheck:
      test: curl -f http://localhost:5081/healthcheck || exit 1
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - api
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 500M
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    external:
      name: trivialsec
